# Generated by Django 3.0.8 on 2020-07-20 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('storage', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('price', models.IntegerField()),
                ('display', models.CharField(max_length=100)),
                ('image', models.FilePathField(path='PROKART/phones_img/')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('E', 'Excellent'), ('VG', 'Very Good'), ('G', 'Good'), ('P', 'Poor'), ('VP', 'Very Poor')], max_length=2)),
                ('vote', models.IntegerField(default=0)),
                ('vote_percent', models.IntegerField(default=0)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PROKART.Phones')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PROKART.Phones')),
            ],
        ),
    ]
