# Generated by Django 3.0.8 on 2020-07-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROKART', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='image',
            field=models.FilePathField(path='/img'),
        ),
    ]
