# Generated by Django 3.0.8 on 2020-07-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROKART', '0002_auto_20200720_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='image',
            field=models.FilePathField(path='PROKART/static/img'),
        ),
    ]
