# Generated by Django 3.0.8 on 2020-07-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROKART', '0005_auto_20200720_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='phone',
            new_name='phones',
        ),
        migrations.AlterField(
            model_name='phones',
            name='image',
            field=models.FilePathField(path='PROKART/static/img/'),
        ),
    ]
