# Generated by Django 3.0.8 on 2020-07-24 11:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PROKART', '0006_auto_20200723_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_on',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 7, 24, 11, 34, 3, 328554, tzinfo=utc)),
        ),
    ]
