# Generated by Django 3.0.8 on 2020-07-24 11:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PROKART', '0007_auto_20200724_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 24, 11, 36, 3, 928976, tzinfo=utc)),
        ),
    ]
