# Generated by Django 3.0.8 on 2020-07-30 17:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PROKART', '0008_auto_20200724_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 30, 17, 12, 52, 60855, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='name',
            field=models.CharField(choices=[('E', 'EXCELLENT'), ('VG', 'Very Good'), ('G', 'Good'), ('P', 'Poor'), ('VP', 'Very Poor')], max_length=2),
        ),
    ]
